code --install-extension abusaidm.html-snippets
code --install-extension akamud.vscode-javascript-snippet-pack
code --install-extension akamud.vscode-theme-onedark
code --install-extension azemoh.one-monokai
code --install-extension bradlc.vscode-tailwindcss
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension EQuimper.react-native-react-redux
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gencer.html-slim-scss-css-class-completion
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension steoates.autoimport
code --install-extension stylelint.vscode-stylelint
code --install-extension syler.sass-indented
code --install-extension tobiasalthoff.atom-material-theme
code --install-extension WakaTime.vscode-wakatime
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension Zignd.html-css-class-completion
